/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package git_481odev1;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        search(new ArrayList<Integer>(), 2);
        System.out.println("aaaaa");    
    }

    public static boolean search(ArrayList<Integer> array, int e) {
        System.out.println("inside search");
        if (array == null) return false;
  
        for (int elt : array) {
          if (elt == e) return true;
        }
        return false;
      }

}
